stages:
  data_collection:
    cmd: python src/data/data_collection.py
    deps:
    - src/data/data_collection.py
    params:
    - data_collection.test_size
    outs:
    - data/raw/
  pre_processing:
    cmd: python src/data/data_prep.py
    deps:
    - data/raw/
    - src/data/data_prep.py
    outs:
    - data/processed/
  model_building:
    cmd: python src/model/model_building.py
    deps:
    - data/processed/
    - src/model/model_building.py
    params:
    - model_building.n_estimators
    outs:
    - models/model_median.pkl
    - reports/run_info.json

    

  model_eval:
    cmd: python src/model/model_eval.py
    deps:
    - models/model_median.pkl
    - src/model/model_eval.py
    metrics:
    - reports/metrics_median.json
 
    


  model_registration:
    cmd: python src/model/model_reg.py
    deps:
    - reports/run_info.json
    - src/model/model_reg.py

