name: CICD

on: push

jobs: 
    Continous-Intergration: 
                   runs-on: ubuntu-latest
                   steps:
                      - name: Checkout Code
                        uses: actions/checkout@v3

                      - name: Setup Python
                        uses: actions/setup-python@v4
                        with:
                          python-version: "3.12"
                      
                      - name: Install Dependecies
                        run: |
                            python -m pip install --upgrade pip
                            pip install -r requirements.txt
                            pip install dvc
                      
                      - name: DVC Authentication with DagsHub
                        run: |
                              dvc remote modify --local access_key_id 9a0cfdb8c9f9890d8d9e80455ae5918fcb9f4cb6
                      #       dvc remote modify myremote account_name AM-Ankitgit
                      #       dvc remote modify password "${{ secrets.DAGSHUB_TOKEN }}"





                      - name: Run CI
                        run: |
                          dvc repro


