name: CICD

on: push

jobs: 
    Continous-Intergration: 
                   runs-on: ubuntu-latest
                   steps:
                      - name: Checkout Code
                        uses: actions/checkout@v3

                      - name: Setup Python
                        uses: actions/setup-python@v4
                        with:
                          python-version: "3.12"
                      
                      - name: Install Dependecies
                        run: |
                            python -m pip install --upgrade pip
                            pip install -r requirements.txt
                      
                      # - name: DVC Authentication with DagsHub
                      #   run: |
                      #       dvc remote modify myremote account_name AM-Ankitgit
                      #       dvc remote modify password "${{ secrets.DAGSHUB_TOKEN }}"


                      - name: Run CI
                        run: |
                          dvc repro


