name: CICD

on: push

jobs: 
    Continous-Intergration: 
                   runs-on: ubnutu-latest
                   steps:
                      - name: Checkout Code
                        uses: actions/checkout@v3

                      - name: Setup Python
                        uses: actions/setup-python@v4
                      
                      - name: Install Dependecies
                        run: |
                            python -m pip install --upgrade pip
                            pip install -r requirements.txt
                      - name: Run CI
                        run: |
                          dvc repro


