name: CICD

on: push

jobs: 
    Continous-Intergration: 
                   runs-on: ubuntu-latest
                   steps:
                      - name: Checkout Code
                        uses: actions/checkout@v3

                      - name: Setup Python
                        uses: actions/setup-python@v4
                        with:
                          python-version: "3.12"
                      
                      - name: Install Dependecies
                        run: |
                            python -m pip install --upgrade pip
                            pip install -r requirements.txt
                      
                      - name: DVC Authentication with DagsHub
                      
                        run: |
                          dvc remote modify origin auth basic
                          dvc remote modify origin user AM-Ankitgit
                          dvc remote modify origin password "${{ secrets.DAGSHUB_TOKEN }}"

                      - name: Run CI
                        run: |
                          dvc repro


